# Generated by Django 5.2.6 on 2025-09-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mfa_backup_codes',
            field=models.TextField(blank=True, help_text='JSON array of backup codes'),
        ),
    ]
