# Generated by Django 5.2.6 on 2025-09-08 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '__first__'),
        ('orders', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APITokenPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(choices=[('week', '1 Week'), ('month', '1 Month'), ('year', '1 Year')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('api_calls_per_month', models.IntegerField(default=1000)),
                ('concurrent_connections', models.IntegerField(default=1)),
                ('includes_real_time_data', models.BooleanField(default=True)),
                ('includes_historical_data', models.BooleanField(default=False)),
                ('includes_analytics', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Token Package',
                'verbose_name_plural': 'API Token Packages',
                'db_table': 'subscriptions_apitokenpackage',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserAPIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('api_calls_used', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_tokens', to='orders.orderitem')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.apitokenpackage')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_token', to='authtoken.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Token',
                'verbose_name_plural': 'User API Tokens',
                'db_table': 'subscriptions_userapitoken',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_bd8750_idx'), models.Index(fields=['expires_at'], name='subscriptio_expires_b98fc1_idx')],
            },
        ),
    ]
