# Generated by Django 5.2.6 on 2025-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='environmental_matrix',
            field=models.TextField(blank=True, help_text='Environmental impact and sustainability information (e.g., CO2 effect, energy efficiency, recyclability)', null=True, verbose_name='Environmental Matrix'),
        ),
    ]
